name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        bundler-cache: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips-dev libpq-dev build-essential libssl-dev libreadline-dev zlib1g-dev
      
    - name: Start PostgreSQL with Docker Compose
      run: docker-compose up -d
      
    - name: Fix line ending issues in scripts (if needed)
      run: |
        chmod +x bin/*
        
    - name: Setup Application
      run: |
        bin/setup
        
    - name: Start Rails server in background
      run: |
        bin/dev &
        sleep 30  # Give the server time to start up
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Playwright dependencies
      working-directory: ./playwright-test
      run: |
        npm install
        npx playwright install --with-deps
        
    - name: Run Playwright tests
      working-directory: ./playwright-test
      run: npx playwright test
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-test/playwright-report/
        retention-days: 30
